### PR TITLE
3x dev merge

### PR DESCRIPTION
**Pull request by jordimontana82**
**What issue does this PR address?**

**Important: Any code or remarks in your Pull Request are under the following terms:**

You acknowledge and agree that by submitting a request or making any code, comment, remark, feedback, enhancements, or modifications proposed or suggested by You in your pull request, You are deemed to accept the terms of our [Contributor License Agreement (CLA)](https://github.com/DynamicsValue/licence-agreements/blob/main/FakeXrmEasy/CLA.md) and that the CLA document is fully enforceable and effective for You.

### CODE REVIEW

**Comment by jordimontana82** [comment]
recheck

**Comment by bwmodular** [comment]
Could be! I’ll check later - but what do we do if it is as I’ve already committed the change with that git username in the config…?

**Comment by jordimontana82** [comment]
I'm guessing pull this branch, revert that commit, update email / username, and commit again...

**Comment by bwmodular** [comment]
Yes, merging this one probably much less time consuming. I've fixed my local git config so it shouldn't happen again! :-)

**Pull request merged**
